name: CD - Production Deploy

# mainブランチに「合流（push/merge）」した時だけ動く！
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cd-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect AWS with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211813536585:role/github-actions-real-flow-role
          aws-region: ap-northeast-1

      - name: Deploy to AWS
        run: |
          echo "【CD起動】AWSへの本番デプロイコマンドを実行します。"
          aws sts get-caller-identity